CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [GRUPADI] NVARCHAR(30) NULL, 
    [GRUPKODU] NVARCHAR(30) NULL, 
    [SAVEDATE] DATETIME NULL, 
    [SAVEUSER] INT NULL, 
    [EDITDATE] DATETIME NULL, 
    [EDITUSER] INT NULL
)
