//------------------------------------------------------------------------------
// < auto - generated >
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000

//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace Odev.Properties
//{
//    using System;


//    / <summary>
//    /   A strongly-typed resource class, for looking up localized strings, etc.
//    / </summary>
//     This class was auto-generated by the StronglyTypedResourceBuilder
//     class via a tool like ResGen or Visual Studio.
//     To add or remove a member, edit your.ResX file then rerun ResGen
//     with the /str option, or rebuild your VS project.
//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    internal class Resources
//    {

//        private static global::System.Resources.ResourceManager resourceMan;

//        private static global::System.Globalization.CultureInfo resourceCulture;

//        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
//        internal Resources()
//        {

//        }

//        / <summary>
//        /   Returns the cached ResourceManager instance used by this class.
//        / </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Resources.ResourceManager ResourceManager
//        {
//            get
//            {
//                if (object.ReferenceEquals(resourceMan, null))
//                {
//                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Odev.Properties.Resources", typeof(Resources).Assembly);
//                    resourceMan = temp;
//                }
//                return resourceMan;
//            }
//        }

//        /// <summary>
//        ///   Overrides the current thread's CurrentUICulture property for all
//        ///   resource lookups using this strongly typed resource class.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Globalization.CultureInfo Culture
//        {
//            get
//            {
//                return resourceCulture;
//            }
//            set
//            {
//                resourceCulture = value;
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap bonote_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("bonote_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap bonote_16x161
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("bonote_16x161", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap bonote_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("bonote_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap bonote_32x321
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("bonote_32x321", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap bonote_32x322
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("bonote_32x322", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap boorderitem_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("boorderitem_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap boorderitem_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("boorderitem_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap boproductgroup_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("boproductgroup_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap boproductgroup_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("boproductgroup_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap boresume_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("boresume_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap boresume_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("boresume_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap bosale_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("bosale_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap bosale_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("bosale_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap chartsshowlegend_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("chartsshowlegend_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap chartsshowlegend_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("chartsshowlegend_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap chartsshowlegend_32x321
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("chartsshowlegend_32x321", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap contact_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("contact_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap contact_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("contact_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap currency_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("currency_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap currency_16x161
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("currency_16x161", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap currency_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("currency_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap currency_32x321
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("currency_32x321", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap editcontact_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("editcontact_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap editcontact_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("editcontact_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap editdatasource_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("editdatasource_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap editdatasource_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("editdatasource_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap financial_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("financial_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap financial_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("financial_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap home_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("home_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap home_16x161
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("home_16x161", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap home_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("home_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap home_32x321
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("home_32x321", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap insert_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("insert_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap insert_16x161
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("insert_16x161", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap insert_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("insert_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap insert_32x321
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("insert_32x321", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap list_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("list_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap list_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("list_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap listmultilevel_righttoleft_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("listmultilevel_righttoleft_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap packageproduct_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("packageproduct_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap packageproduct_16x161
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("packageproduct_16x161", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap packageproduct_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("packageproduct_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap packageproduct_32x321
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("packageproduct_32x321", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap pictureshapeoutlinecolor_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("pictureshapeoutlinecolor_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap pictureshapeoutlinecolor_16x161
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("pictureshapeoutlinecolor_16x161", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap pictureshapeoutlinecolor_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("pictureshapeoutlinecolor_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap pictureshapeoutlinecolor_32x321
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("pictureshapeoutlinecolor_32x321", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap product_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("product_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap product_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("product_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap team_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("team_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap team_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("team_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap today_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("today_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap today_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("today_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap windows_16x16
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("windows_16x16", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));
//            }
//        }

//        /// <summary>
//        ///   Looks up a localized resource of type System.Drawing.Bitmap.
//        /// </summary>
//        internal static System.Drawing.Bitmap windows_32x32
//        {
//            get
//            {
//                object obj = ResourceManager.GetObject("windows_32x32", resourceCulture);
//                return ((System.Drawing.Bitmap)(obj));

//            }
//        }

